import os

from dotenv import load_dotenv

load_dotenv()

DB_MIN_CONN = 1
DB_MAX_CONN = 10
DB_HOST = os.getenv("DB_HOST", "")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "")
DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")

SQL_DIARY_ENTRIES_TABLE_NAME = "diary_entries"
SQL_PATIENTS_TABLE_NAME = "patients"
SQL_HEALTH_ALERTS_TABLE_NAME = "health_alerts"

SQL_CREATE_TABLES = f"""
CREATE TABLE IF NOT EXISTS {SQL_PATIENTS_TABLE_NAME} (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    language_code TEXT,
    taj_number TEXT UNIQUE,
    chronic_illnesses TEXT[],
    allergies TEXT[],
    drug_sensitivities TEXT[],
    date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS {SQL_DIARY_ENTRIES_TABLE_NAME} (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_profile_id INTEGER REFERENCES {SQL_PATIENTS_TABLE_NAME} (id),
    timestamp TIMESTAMP WITH TIME ZONE,
    mood_level INTEGER,
    emotions TEXT[],
    health_complaints TEXT,
    food_intake TEXT,
    notes TEXT,
    suggestions TEXT
);

CREATE TABLE IF NOT EXISTS {SQL_HEALTH_ALERTS_TABLE_NAME} (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_profile_id INTEGER REFERENCES {SQL_PATIENTS_TABLE_NAME} (id),
    title TEXT,
    message TEXT,
    timestamp TIMESTAMP WITH TIME ZONE,
    is_read BOOLEAN,
    severity INTEGER
);
"""

SQL_CREATE_INDICES = f"""
CREATE INDEX IF NOT EXISTS ix_{SQL_DIARY_ENTRIES_TABLE_NAME}_timestamp ON public.{SQL_DIARY_ENTRIES_TABLE_NAME} (timestamp);
CREATE INDEX IF NOT EXISTS ix_{SQL_PATIENTS_TABLE_NAME}_taj_number ON public.{SQL_PATIENTS_TABLE_NAME} (taj_number);
CREATE INDEX IF NOT EXISTS ix_{SQL_HEALTH_ALERTS_TABLE_NAME}_timestamp ON public.{SQL_HEALTH_ALERTS_TABLE_NAME} (timestamp);
"""

SQL_INSERT_DIARY_ENTRY_RETURNING_ID = f"""
INSERT INTO {SQL_DIARY_ENTRIES_TABLE_NAME} (timestamp, patient_profile_id, mood_level, emotions, health_complaints, food_intake, notes, suggestions)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
RETURNING id;
"""

SQL_INSERT_PATIENT_RETURNING_ID = f"""
INSERT INTO {SQL_PATIENTS_TABLE_NAME} (name, language_code, taj_number, chronic_illnesses, allergies, drug_sensitivities, date_of_birth)
VALUES (%s, %s, %s, %s, %s, %s, %s)
RETURNING id;
"""

SQL_INSERT_HEALTH_ALERT_RETURNING_ID = f"""
INSERT INTO {SQL_HEALTH_ALERTS_TABLE_NAME} (patient_profile_id, title, message, timestamp, is_read, severity)
VALUES (%s, %s, %s, %s, %s, %s)
RETURNING id;
"""
