import os

DB_MIN_CONN = 1
DB_MAX_CONN = 10
DB_HOST = os.getenv("DB_HOST", "")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "")
DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")

SQL_CREATE_TABLES = """
CREATE TABLE IF NOT EXISTS diary_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP WITH TIME ZONE,
    mood_level INTEGER,
    emotions TEXT[],
    health_complaints TEXT,
    food_intake TEXT,
    notes TEXT,
    suggestions TEXT
);

CREATE TABLE IF NOT EXISTS patients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    language_code TEXT,
    taj_number TEXT UNIQUE,
    chronic_illnesses TEXT[],
    allergies TEXT[],
    drug_sensitivities TEXT[],
    date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS health_alerts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT,
    message TEXT,
    timestamp TIMESTAMP WITH TIME ZONE,
    is_read BOOLEAN,
    severity INTEGER
);
"""

SQL_CREATE_INDICES = """
CREATE INDEX IF NOT EXISTS ix_diary_entries_timestamp ON public.diary_entries (timestamp);
CREATE INDEX IF NOT EXISTS ix_patients_taj_number ON public.patients (taj_number);
CREATE INDEX IF NOT EXISTS ix_health_alerts_timestamp ON public.health_alerts (timestamp);
"""
