CREATE TABLE IF NOT EXISTS diary_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP WITH TIME ZONE,
    mood_level INTEGER,
    emotions TEXT[],
    health_complaints TEXT,
    food_intake TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS patients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    language_code TEXT,
    taj_number TEXT UNIQUE,
    chronic_illnesses TEXT[],
    allergies TEXT[],
    drug_sensitivities TEXT[],
    date_of_birth DATE
);

CREATE INDEX IF NOT EXISTS ix_diary_entries_timestamp ON public.diary_entries (timestamp);
CREATE INDEX IF NOT EXISTS ix_patients_taj_number ON public.patients (taj_number);
